name: Test React App
on: push
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test
